---
kind: pipeline
type: docker
name: build

steps:
- name: install
  image: node:12
  commands:
  - cd $${PREFIX} && npm install
  environment:
    PREFIX: ./Frontend/ProtectTheDough.Web/ClientApp

- name: linting
  image: node:12
  commands:
  - cd $${PREFIX}
  - npm run lint
  environment:
    PREFIX: ./Frontend/ProtectTheDough.Web/ClientApp

- name: build
  image: node:12
  commands:
  - cd $${PREFIX}
  - npm --prefix /usr install -g @angular/cli
  - ng --version
  - node -v
  - npm -v
  - npm run build-prod
  environment:
    PREFIX: ./Frontend/ProtectTheDough.Web/ClientApp

trigger:
  branch:
  - master
  event:
    include:
    - push
    - pull_request

---
kind: pipeline
type: exec
name: deploy

steps:
- name: node_modules
  commands:
  - cd Frontend/ProtectTheDough.Web/ClientApp
  - npm install --cache /tmp/empty-cache

- name: pack
  commands:
  - cd ./Frontend
  - dotnet publish -c Release

- name: clean
  commands:
  - rm -rf /tmp/empty-cache
  - rm -rf /var/www/html/angular/*

- name: publish
  commands:
  - cp -r ./Frontend/ProtectTheDough.Web/bin/Release/netcoreapp3.0/publish/* /var/www/html/angular/

trigger:
  branch:
  - master
  event:
    include:
    - push

depends_on:
- build

---
kind: signature
hmac: 97d720ed72399140d3237d43ac2dc5f890e817cb7c5ee41e593feb88854990fa

...
