kind: pipeline
name: default

steps:
- name: install
  image: node:12
  commands:
  - cd $${PREFIX} && npm install
  - npm --prefix /usr install -g @angular/cli
  
- name: linting
  commands:
  - npm run lint
  
- name: build
  commands:
  - ng --version
  - ng build
  environment:
    PREFIX: ./Frontend/ProtectTheDough.Web/ClientApp
  
trigger:
  branch:
  - master
  event:
    include:
    - push
    - pull_request
