kind: pipeline
type: docker
name: default

steps:
  install:                         
    image: node                    
    commands:                      
      - npm install -g @angular/cli
      - npm install                
  build:                           
    image: node                    
    commands:
      - npm audit fix
      #- npm run lint               
      #- ng build     

trigger:
  branch:
    - master