kind: pipeline
name: default

steps:
- name: install
  image: node:12
  commands:
  - npm --prefix $${PREFIX}/node_modules install $${PREFIX}
  environment:
    PREFIX: ./Frontend/ProtectTheDough.Web/ClientApp
  
- name: build
  image: node:12
  commands:
  - npm install -g @angular/cli
  - ng build
  environment:
    PREFIX: ./Frontend/ProtectTheDough.Web/ClientApp
  
trigger:
  branch:
  - master
  event:
    include:
    - push
    - pull_request
