---
kind: pipeline
type: docker
name: build

steps:
- name: install
  image: node:12
  commands:
  - cd $${PREFIX} && npm install
  environment:
    PREFIX: ./Frontend/ProtectTheDough.Web/ClientApp

- name: linting
  image: node:12
  commands:
  - cd $${PREFIX}
  - npm run lint
  environment:
    PREFIX: ./Frontend/ProtectTheDough.Web/ClientApp

- name: build
  image: node:12
  commands:
  - cd $${PREFIX}
  - npm --prefix /usr install -g @angular/cli
  - ng --version
  - node -v
  - npm -v
  - npm run build-prod
  environment:
    PREFIX: ./Frontend/ProtectTheDough.Web/ClientApp

trigger:
  branch:
  - master
  event:
    include:
    - push
    - pull_request

---
kind: pipeline
type: exec
name: deploy

steps:
- name: clean
  commands:
  - rm -rf /var/www/html/angular/*

- name: install_modules
  commands:
  - cd Frontend/ProtectTheDough.Web/ClientApp
  - which npm
  - which node
  - echo $NODE_PATH
  - whoami
  - temppath=$PATH
  - PATH=$(pwd)/node_modules:$PATH
  - npm cache clean
  - npm install --verbose
  - cd ../..

- name: pack
  commands:
  - cd Frontend
  - dotnet publish -c Release
  - PATH=$temppath

- name: publish
  commands:
  - cp -r ProtectTheDough.Web/bin/Release/netcoreapp3.0/publish /var/www/html/angular/

trigger:
  branch:
  - master
  event:
    include:
    - push

depends_on:
- build

---
kind: signature
hmac: fa2e41e4a1e6462030d498528070eb4c8e8aa20371ac4a6987b5e8b20a56fa62

...
