---
kind: pipeline
type: exec
name: deploy

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: clean
  commands:
  - rm -rf ./Frontend/ProtectTheDough.Web/bin/Release/netcoreapp3.0
  - rm -rf ./Frontend/ProtectTheDough.Web/ClientApp/dist

- name: pack
  commands:
  - cd ./Frontend
  - dotnet publish -c Release

- name: publish
  commands:
  - rm -rf /var/www/html/angular/*
  - cp -r ./Frontend/ProtectTheDough.Web/bin/Release/netcoreapp3.0/publish /var/www/html/angular/

trigger:
  branch:
  - master
  event:
    include:
    - push

depends_on:
- build

---
kind: pipeline
type: docker
name: build

steps:
- name: install
  image: node:12
  commands:
  - cd $${PREFIX} && npm install
  environment:
    PREFIX: ./Frontend/ProtectTheDough.Web/ClientApp

- name: linting
  image: node:12
  commands:
  - cd $${PREFIX}
  - npm run lint
  environment:
    PREFIX: ./Frontend/ProtectTheDough.Web/ClientApp

- name: build
  image: node:12
  commands:
  - cd $${PREFIX}
  - npm --prefix /usr install -g @angular/cli
  - ng --version
  - node -v
  - npm -v
  - npm run build-prod
  environment:
    PREFIX: ./Frontend/ProtectTheDough.Web/ClientApp

trigger:
  branch:
  - master
  event:
    include:
    - push
    - pull_request

---
kind: signature
hmac: 6c73ca65e6636958aaeb10901f69e76cdeeb6113caeb03dd27a360d713c8d5cc

...
