kind: pipeline
name: default

steps:
- name: install
  image: node
  commands:
  - npm --prefix $${PREFIX}/node_modules install $${PREFIX}
  - npm install -g @angular/cli
  environment:
    PREFIX: ./Frontend/ProtectTheDough.Web/ClientApp
  
- name: build
  image: node
  commands:
  - npm --prefix $${PREFIX} run build
  environment:
    PREFIX: ./Frontend/ProtectTheDough.Web/ClientApp
    PATH: $${PREFIX}/node_modules/@angular/cli/bin:${PATH}
  
trigger:
  branch:
  - master
  event:
    include:
    - push
    - pull_request
