---
kind: pipeline
type: docker
name: build

steps:
- name: install
  image: node:12
  commands:
  - cd $${PREFIX} && npm install
  environment:
    PREFIX: ./Frontend/ProtectTheDough.Web/ClientApp

- name: linting
  image: node:12
  commands:
  - cd $${PREFIX}
  - npm run lint
  environment:
    PREFIX: ./Frontend/ProtectTheDough.Web/ClientApp

- name: build
  image: node:12
  commands:
  - cd $${PREFIX}
  - npm --prefix /usr install -g @angular/cli
  - ng --version
  - node -v
  - npm -v
  - npm run build-prod
  environment:
    PREFIX: ./Frontend/ProtectTheDough.Web/ClientApp

trigger:
  branch:
  - master
  event:
    include:
    - push
    - pull_request

---
kind: pipeline
type: exec
name: deploy

steps:
- name: node_modules
  commands:
  - cd Frontend/ProtectTheDough.Web/ClientApp
  - npm install --cache /tmp/empty-cache

- name: pack
  commands:
  - cd ./Frontend
  - dotnet publish -c Release

- name: clean
  commands:
  - rm -rf /tmp/empty-cache
  - rm -rf /var/www/html/angular/*

- name: publish
  commands:
  - cp -r ./Frontend/ProtectTheDough.Web/bin/Release/netcoreapp3.0/publish/* /var/www/html/angular/

trigger:
  branch:
  - master
  event:
    include:
    - push

depends_on:
- build

---
kind: pipeline
type: exec
name: backend

steps:
- name: clean
  commands:
  - docker container stop express-backend
  - docker container rm express-backend
  - docker image rm nick/express-backend --force
  environment:
    PASS:
      from_secret: password

- name: build-image
  commands:
  - cd Backend
  - docker build -t nick/express-backend .

- name: run-container
  commands:
  - docker run -d --name express-backend -p 3030:3000 nick/express-backend

  environment:
    PASS:
      from_secret: password

trigger:
  branch:
  - master
  event:
    include:
    - push
---
kind: signature
hmac: 57532ee6f199e455e83723a8719dbd9d7913e5370d945ec1b86e85565f5b9604

---
kind: secret
name: password
data: iWUg/vO+G9JkIp6WfG/hOmV5eZOhVAU/VCsq7fCkglzsOg==
...
